-- 创建任务实例
CALL CREATE_TABLES('JOB_INSTANCE','CREATE TABLE `JOB_INSTANCE` (
	`ID` BIGINT NOT NULL,
	`JOB_ID` BIGINT NOT NULL,
	`APP_ID` VARCHAR(50) NOT NULL,
	`TRIGGER_TIME` DATETIME NOT NULL,
	`EXECUTE_TIME` DATETIME NOT NULL,
	`STATE` TINYINT NOT NULL,
	`CREATE_TIME` DATETIME NOT NULL,
	`CREATOR` BIGINT NULL,
	`REVISE_TIME` DATETIME NULL,
	`REVISER` BIGINT NULL,
	`TENANT_ID` BIGINT NULL,
	PRIMARY KEY (`ID`)
	);'
);
-- 设置注释任务实例
CALL MODIFY_TABLE_COMMENTS('JOB_INSTANCE', '任务实例|任务实例');
-- 设置注释任务实例
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'ID', '主键|主键');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'JOB_ID', 'jobId|jobId');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'APP_ID', '应用|应用');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'TRIGGER_TIME', '触发时间|触发时间');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'EXECUTE_TIME', '执行时间|执行时间');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'STATE', '是否终止 0：未终止1：已终止（不在执行）|是否终止 0：未终止1：已终止（不在执行）');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'CREATE_TIME', '创建时间|创建时间');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'CREATOR', '创建人|创建人');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'REVISE_TIME', '修改时间|修改时间');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'REVISER', '修改人|修改人');
CALL MODIFY_COLUMNS_COMMENTS('JOB_INSTANCE', 'TENANT_ID', '租户|租户');
-- 设置默认值任务实例
CALL MODIFY_COLUMNS_DEFAULT('JOB_INSTANCE', 'STATE', '0');
CALL MODIFY_COLUMNS_DEFAULT('JOB_INSTANCE', 'TENANT_ID', '0');
